# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.5
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 日志配置
logging:
  level:
    org.springframework: warn
    io.github.lyk98.fast: info

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry
    username: root
    password: 123456
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: io.github.lyk98.fast.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: a1b2c3E4F5G61126aa1126bb1126cca1b2c3E4F5G61126aa1126bb1126cc1126aa1126bb1126cc1126aa1126bb1126cc
  # 令牌有效期（默认30分钟）
  expireTime: 30

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*